import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-4 w-full justify-center border-b p-4">
          <Link href="/">Home</Link>
          <Link href="/one">One</Link>
          <Link href="/two">Two</Link>
          <Link href="/three">Three (dynamic)</Link>
          <Link href="/four">Four (dynamic)</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
