import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PropsWithChildren, Suspense } from "react";
import Cart from "./cart";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "nl" }];
}

export default function RootLayout({
  children,
  params: { locale },
}: PropsWithChildren<{ params: { locale: string } }>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <nav className="flex gap-4 w-full justify-center border-b p-4">
          <Link href="/">Home</Link>
          <Link href="/one">One</Link>
          <Link href="/two">Two</Link>
          <Link href="/dynamic/three">Three (dynamic)</Link>
          <Link href="/dynamic/four">Four (dynamic)</Link>
          <Suspense fallback="No cart">
            <Cart />
          </Suspense>
        </nav>
        {children}
      </body>
    </html>
  );
}
