import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { PropsWithChildren, Suspense } from "react";
import { Link } from "@/navigation";
import { unstable_setRequestLocale } from "next-intl/server";
import Cart from "./cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "nl" }];
}

export default function RootLayout({
  children,
  params: { locale },
}: PropsWithChildren<{ params: { locale: string } }>) {
  unstable_setRequestLocale(locale);
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <nav className="flex gap-4 w-full justify-center border-b p-4">
          <Link href="/">Home</Link>
          <Link href="/one">One</Link>
          <Link href="/two">Two</Link>
          <Link
            href={{
              pathname: "/dynamic/[dynamic]",
              params: { dynamic: "three" },
            }}
          >
            Three (dynamic)
          </Link>
          <Link
            href={{
              pathname: "/dynamic/[dynamic]",
              params: { dynamic: "four" },
            }}
          >
            Four (dynamic)
          </Link>
          <Suspense fallback="No cart">
            <Cart />
          </Suspense>
        </nav>
        {children}
      </body>
    </html>
  );
}
